services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    ports:
      - '8787:8787'
    volumes:
      - meta-sovereign-data:/data
  rtc:
    build:
      context: ..
      dockerfile: docker/rtc.Dockerfile
    ports:
      - '8788:8788'
    volumes:
      - meta-sovereign-data:/data

volumes:
  meta-sovereign-data: {}
